name: SummaryL
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anaconda-anon-usage=0.7.2=py313hd6b623d_100
  - anaconda-auth=0.8.6=py313hca03da5_0
  - anaconda-cli-base=0.5.2=py313hca03da5_0
  - annotated-types=0.6.0=py313hca03da5_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - boltons=25.0.0=py313hca03da5_0
  - brotlicffi=1.0.9.2=py313h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313hca03da5_0
  - colorama=0.4.6=py313hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - conda=25.9.1=py313h8f79df9_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313hca03da5_1
  - conda-content-trust=0.2.0=py313hca03da5_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313hca03da5_0
  - conda-package-streaming=0.12.0=py313hca03da5_0
  - cpp-expected=1.1.0=h48ca7d4_0
  - cpython=3.13.9=py313hd8ed1ab_100
  - cryptography=45.0.5=py313hace6d20_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py313hca03da5_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fmt=9.1.0=h48ca7d4_1
  - frozendict=2.4.2=py313hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py313hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=py313hca03da5_0
  - jaraco.context=6.0.0=py313hca03da5_0
  - jaraco.functools=4.1.0=py313hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=py313hca03da5_1
  - jsonpointer=3.0.0=py313hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyring=25.6.0=py313hca03da5_0
  - krb5=1.21.3=h237132a_0
  - libarchive=3.7.7=h8f13d7a_0
  - libcurl=8.14.1=hcdd2897_1
  - libcxx=19.1.7=hb09ecce_3
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.16=h80987f9_3
  - libmamba=2.0.5=h15e39b3_1
  - libmambapy=2.0.5=py313h48ca7d4_1
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libsodium=1.0.20=h99b78c6_0
  - libsolv=0.7.30=h514c7bf_1
  - libssh2=1.11.1=h3e2b118_0
  - libxml2=2.13.8=h0b34f26_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py313hca03da5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py313hca03da5_0
  - menuinst=2.3.1=py313hca03da5_0
  - more-itertools=10.3.0=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h313beb8_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=py313hca03da5_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pkce=1.0.3=py313hca03da5_0
  - platformdirs=4.3.7=py313hca03da5_0
  - pluggy=1.5.0=py313hca03da5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py313h6535dbc_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h80987f9_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313hca03da5_0
  - pydantic-core=2.33.2=py313h5e3a92f_0
  - pydantic-settings=2.6.1=py313hca03da5_0
  - pygments=2.19.1=py313hca03da5_0
  - pyjwt=2.10.1=py313hca03da5_0
  - pysocks=1.7.1=py313hca03da5_0
  - python=3.13.5=h2eb94d5_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313hca03da5_0
  - python-gil=3.13.9=h4df99d1_100
  - python.app=3=py313h80987f9_2
  - python_abi=3.13=0_cp313
  - pyzmq=27.1.0=py312hd65ceae_0
  - readchar=4.0.5=py313hca03da5_0
  - readline=8.3=h0b18652_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.4=py313hca03da5_0
  - rich=13.9.4=py313hca03da5_0
  - ruamel.yaml=0.18.10=py313h80987f9_0
  - ruamel.yaml.clib=0.2.12=py313h80987f9_0
  - semver=3.0.2=py313hca03da5_1
  - setuptools=78.1.1=py313hca03da5_0
  - shellingham=1.5.0=py313hca03da5_0
  - simdjson=3.10.1=h48ca7d4_0
  - six=1.17.0=pyhe01879c_1
  - spdlog=1.11.0=h48ca7d4_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py313hca03da5_0
  - tornado=6.5.2=py313hcdf3177_1
  - tqdm=4.67.1=py313h7eb115d_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=py313hca03da5_0
  - typer=0.9.0=py313hca03da5_0
  - typing-extensions=4.12.2=py313hca03da5_0
  - typing-inspection=0.4.0=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - urllib3=2.5.0=py313hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - zstandard=0.23.0=py313h1a4646a_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - absl-py==2.4.0
      - altair==6.0.0
      - anyio==4.12.1
      - arviz==0.23.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - bayesflow==2.0.8
      - blessed==1.22.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - cloudpickle==3.1.2
      - cons==0.4.7
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2026.1.2
      - distributed==2026.1.2
      - enlighten==1.14.1
      - etuples==0.3.10
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.60.1
      - fsspec==2026.1.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5netcdf==1.8.1
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - jabbar==0.0.16
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - keras==3.13.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - llvmlite==0.46.0
      - locket==1.0.0
      - logical-unification==0.4.7
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - minikanren==1.0.5
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multipledispatch==1.0.0
      - namex==0.1.0
      - narwhals==2.16.0
      - networkx==3.6.1
      - nflows==0.14
      - nsz==4.6.1
      - numba==0.63.1
      - numpy==2.3.4
      - ollama==0.6.1
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - partd==1.4.2
      - pillow==12.0.0
      - pip==26.0
      - pot==0.9.6.post1
      - prefixed==0.9.0
      - protobuf==6.33.5
      - pyabc==0.12.16
      - pyarrow==23.0.0
      - pycryptodome==3.23.0
      - pydeck==0.9.1
      - pyknos==0.16.0
      - pymc==5.27.1
      - pyparsing==3.2.5
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.37.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - redis==7.1.0
      - referencing==0.37.0
      - rpds-py==0.30.0
      - sbi==0.25.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.46
      - streamlit==1.53.1
      - sympy==1.14.0
      - tblib==3.2.2
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - toolz==1.1.0
      - torch==2.10.0
      - torchaudio==2.10.0
      - torchvision==0.25.0
      - tzdata==2025.3
      - uv==0.9.28
      - werkzeug==3.1.5
      - wrapt==2.1.0
      - xarray==2026.1.0
      - xarray-einstats==0.9.1
      - zict==3.0.0
      - zuko==1.5.0
prefix: /Users/mike-fx/miniconda3
